name: Enforce PR Source Branch to Production

on:
  pull_request:
    branches: [Production]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if PR is not from testing branch
        run: |
          if [ "${{ github.head_ref }}" != "Testing" ]; then
            echo "Only PRs from 'Testing' branch are allowed."
            exit 1
          fi
